
import java.text.DecimalFormat;

/*
 * This program is designed to be able to convert measurments the use inputs into different 
 * measurments based on the type of conversion the user chooses 
 */

/**
 * May 3, 2018
 * @author seden0957
 */
public class Display extends javax.swing.JFrame {

    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        convesionChoiceLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        outputLabel = new javax.swing.JLabel();
        systemChoice = new javax.swing.JTextField();
        valueInput = new javax.swing.JTextField();
        inchToCentiLabel = new javax.swing.JLabel();
        feetToCentiLabel = new javax.swing.JLabel();
        yardsToMetresLabel = new javax.swing.JLabel();
        milesToKmLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("Conversion Program");

        convesionChoiceLabel.setText("Enter conversion choice (1-4):");

        valueLabel.setText("Enter value to be converted:");

        enterButton.setText("Convert");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        outputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        inchToCentiLabel.setText("1. Inches to Centimetres");

        feetToCentiLabel.setText("2. Feet to Centimetres");

        yardsToMetresLabel.setText("3. Yards to Metres");

        milesToKmLabel.setText("4. Miles to Kilometres ");

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(displayPanelLayout.createSequentialGroup()
                    .addGap(163, 163, 163)
                    .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(inchToCentiLabel)
                        .addComponent(yardsToMetresLabel)
                        .addComponent(feetToCentiLabel)
                        .addComponent(milesToKmLabel))
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(displayPanelLayout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(title))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                                .addComponent(valueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enterButton)
                                    .addComponent(valueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(displayPanelLayout.createSequentialGroup()
                            .addComponent(convesionChoiceLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(systemChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(208, 208, 208)))
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(title)
                .addGap(28, 28, 28)
                .addComponent(inchToCentiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feetToCentiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yardsToMetresLabel)
                .addGap(4, 4, 4)
                .addComponent(milesToKmLabel)
                .addGap(31, 31, 31)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convesionChoiceLabel)
                    .addComponent(systemChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel)
                    .addComponent(valueInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        DecimalFormat x = new DecimalFormat ("$###.00"); //makes sure if the number is a decimal it isn't too big
        double inchToCenti, feetToCenti, yardsToMetres, milesToKm;
        int conversionChoice;
        conversionChoice = Integer.parseInt(systemChoice.getText()); //based on input 1-4 chooses the system
        switch(conversionChoice)
        {
                case 1:
                    inchToCenti = Double.parseDouble(valueInput.getText()); //get the input
                    inchToCenti = inchToCenti*2.54; //convert inches to centimetres
                    outputLabel.setText(x.format(inchToCenti));
                    break;

                case 2:    
                    feetToCenti = Double.parseDouble(valueInput.getText());//get the input
                    feetToCenti = feetToCenti*30; //feet to centimetres 
                    outputLabel.setText(x.format(feetToCenti));
                    break;

                case 3:
                    yardsToMetres = Double.parseDouble(valueInput.getText());//get the input
                    yardsToMetres = yardsToMetres*.91; //yards to metres 
                    outputLabel.setText(x.format(yardsToMetres));
                    break;
                   
                case 4:
                    milesToKm = Double.parseDouble(valueInput.getText());//get the input
                    milesToKm = milesToKm*1.6; //miles to kilometres 
                    outputLabel.setText(x.format(milesToKm));
                    break;
                default:
                    outputLabel.setText("*Notices incorect input* Sorry this isn't one of the conversions. OwO"); //if conversion system isn't 1-4 display this
        }            
        
    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel convesionChoiceLabel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel feetToCentiLabel;
    private javax.swing.JLabel inchToCentiLabel;
    private javax.swing.JLabel milesToKmLabel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JTextField systemChoice;
    private javax.swing.JLabel title;
    private javax.swing.JTextField valueInput;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel yardsToMetresLabel;
    // End of variables declaration//GEN-END:variables
}
